/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.conexionDB;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class frm_Inventario extends javax.swing.JFrame {
conexionDB cn = new conexionDB();
     DefaultTableModel model;
     SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
     String query2; 
     String arrayCat[];
     String idCategoria[];
    public static int  TipoU;
    public frm_Inventario()  throws SQLException {
        initComponents();
        cn.conectarBD();
        this.cbDesde.setDateFormat(formatoFecha);
        this.cbHasta.setDateFormat(formatoFecha);
        this.jTable1.setModel(cn.llenarInventario(this.jTable1));
        this.model = (DefaultTableModel) jTable1.getModel();
    
     this.rbCategoria.setSelected(false);
     this.rbFecha.setSelected(false);
     this.rbNombre.setSelected(false);
     this.rbPrecio.setSelected(false);
     this.cboCategoria.setEnabled(false);
     this.txtMax.setEnabled(false);
     this.txtMin.setEnabled(false);
     this.cbDesde.setEnabled(false);
     this.cbHasta.setEnabled(false);
     this.txtNombre.setEnabled(false);
       
        try {
            cn.conectarBD();
            Statement stmt = cn.conn.createStatement();
            String query = "SELECT idCategoria, categoria_nombre FROM categoria;";
            ResultSet rs = stmt.executeQuery(query);
            arrayCat = new String[10];
            idCategoria= new String[10];
            int i = 0;
            while(rs.next())
            {
                this.cboCategoria.addItem(rs.getString(2));
                arrayCat[i] = rs.getString(1); 
                idCategoria[i]= rs.getString(2);
                i++; 
            }
            this.cboCategoria.setSelectedIndex(1);
            cn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Agg_Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

                    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/images/logo-M&M-64x64.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbFecha = new javax.swing.JRadioButton();
        rbPrecio = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbCategoria = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        rbTodo = new javax.swing.JRadioButton();
        cbDesde = new datechooser.beans.DateChooserCombo();
        cbHasta = new datechooser.beans.DateChooserCombo();
        btnAlertas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");
        setExtendedState(6);
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        buttonGroup1.add(rbFecha);
        rbFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFecha.setText("Fecha");
        rbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPrecio);
        rbPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPrecio.setText("Precio");
        rbPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrecioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNombre);
        rbNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbNombre.setText("Nombre");
        rbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCategoria);
        rbCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbCategoria.setText("Categoría");
        rbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCategoriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Desde:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hasta:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/btnBuscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Minimo:");

        txtMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Maximo:");

        txtMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(rbTodo);
        rbTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbTodo.setSelected(true);
        rbTodo.setText("Todo");
        rbTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodoActionPerformed(evt);
            }
        });

        cbDesde.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        cbDesde.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        cbHasta.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        cbHasta.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        btnAlertas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/btnAlert.png"))); // NOI18N
        btnAlertas.setText("Alertas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rbFecha)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPrecio)
                    .addComponent(jLabel3)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCategoria)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbTodo))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbFecha)
                        .addComponent(rbCategoria)
                        .addComponent(rbPrecio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbTodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/btnRegresar.png"))); // NOI18N
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Proveedor", "Nombre", "Categoria", "Stock", "Precio Compra", "Expira", "Precio Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/btnEditar.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 600, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        cn.conectarBD();
        if (this.rbTodo.isSelected()==true)  {
        this.rbCategoria.setSelected(false);
        this.rbFecha.setSelected(false);
        this.rbNombre.setSelected(false);
        this.rbPrecio.setSelected(false);
          try  {
        this.jTable1.setModel(cn.llenarInventario(this.jTable1));
        this.model = (DefaultTableModel) jTable1.getModel();
        cn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Inventario.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }else if(this.rbNombre.isSelected()==true){
            this.rbCategoria.setSelected(false);
        this.rbFecha.setSelected(false);
        this.rbTodo.setSelected(false);
        this.rbPrecio.setSelected(false);
        
         try {
             cn.conectarBD();
             query2 = "SELECT * FROM producto WHERE(producto_nombre LIKE '%" +this.txtNombre.getText()+ "%');";
            this.jTable1.setModel(cn.buscarProducto(this.jTable1, query2));
            cn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(this.rbCategoria.isSelected()==true){
          try {
              cn.conectarBD();
             query2 = "SELECT * FROM producto WHERE(idCategoria=" +arrayCat[this.cboCategoria.getSelectedIndex()]+ ");";
            this.jTable1.setModel(cn.buscarProducto(this.jTable1, query2));
            cn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(this.rbPrecio.isSelected()==true){
         try {
             cn.conectarBD();
             query2 = "SELECT * FROM producto WHERE(producto_pVenta >="+this.txtMin.getText()+" and producto_pVenta <="+this.txtMax.getText()+");" ;
            this.jTable1.setModel(cn.buscarProducto(this.jTable1, query2));
            cn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }else if(this.rbFecha.isSelected()==true){
          
     try {
         cn.conectarBD();
             query2 = "SELECT * FROM producto WHERE(producto_fechaExp >='"+this.cbDesde.getText()+"' and producto_fechaExp <='"+this.cbHasta.getText()+"');" ;
            this.jTable1.setModel(cn.buscarProducto(this.jTable1, query2));
            cn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Inventario.class.getName()).log(Level.SEVERE, null, ex);
         }
          }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreActionPerformed

            this.cboCategoria.setEnabled(false);
            this.txtMax.setEnabled(false);
            this.txtMin.setEnabled(false);
            this.cbDesde.setEnabled(false);
            this.cbHasta.setEnabled(false);
            this.txtNombre.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_rbNombreActionPerformed

    private void rbTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodoActionPerformed

             this.cboCategoria.setEnabled(false);
            this.txtMax.setEnabled(false);
            this.txtMin.setEnabled(false);
            this.cbDesde.setEnabled(false);
            this.cbHasta.setEnabled(false);
            this.txtNombre.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodoActionPerformed

    private void rbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCategoriaActionPerformed

    this.txtNombre.setEnabled(false);
    this.txtMax.setEnabled(false);
    this.txtMin.setEnabled(false);
    this.cbDesde.setEnabled(false);
    this.cbHasta.setEnabled(false);
    this.cboCategoria.setEnabled(true);
    
            

// TODO add your handling code here:
    }//GEN-LAST:event_rbCategoriaActionPerformed

    private void rbPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrecioActionPerformed

            this.cboCategoria.setEnabled(false);
            this.txtNombre.setEnabled(false);
            this.cbDesde.setEnabled(false);
            this.cbHasta.setEnabled(false);
            this.txtMax.setEnabled(true);
            this.txtMin.setEnabled(true);
    }//GEN-LAST:event_rbPrecioActionPerformed

    private void rbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaActionPerformed

            this.cboCategoria.setEnabled(false);
            this.txtMax.setEnabled(false);
            this.txtMin.setEnabled(false);
            this.txtNombre.setEnabled(false);
            this.cbDesde.setEnabled(true);
            this.cbHasta.setEnabled(true);
    }//GEN-LAST:event_rbFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if (TipoU==1){
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        if (this.jTable1.getSelectedRows().length ==1) {
            
 frm_Edit_Pro EP=new frm_Edit_Pro();

             EP.show();

          int a =jTable1.getSelectedRow();
          frm_Edit_Pro.txtCode.setText(String.valueOf(model.getValueAt(a,0)));
          frm_Edit_Pro.txtNombre.setText(String.valueOf(model.getValueAt(a,2)));
          frm_Edit_Pro.txtStock.setText(String.valueOf(model.getValueAt(a,4)));
          frm_Edit_Pro.txtPrecioV.setText(String.valueOf(model.getValueAt(a,7)));
        }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                  try {
                new frm_Inventario().setVisible(true);
                 }catch (SQLException ex) {
                        Logger.getLogger(frm_Ver_Proveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo cbDesde;
    private datechooser.beans.DateChooserCombo cbHasta;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JTable jTable1 = new javax.swing.JTable();
    private javax.swing.JRadioButton rbCategoria;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JRadioButton rbPrecio;
    private javax.swing.JRadioButton rbTodo;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
