/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.conexionDB;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class frm_Hist_Venta extends javax.swing.JFrame {
    conexionDB cn = new conexionDB();
    DefaultTableModel model;
    DefaultTableModel modeloDetalle;
   DateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    public frm_Hist_Venta() throws SQLException {
        initComponents();
        this.jtVenta.setSelectionForeground(Color.white);
        this.jtDetalle.setSelectionForeground(Color.white);
        this.fecha1.setDateFormat(formatoFecha);
        this.fecha2.setDateFormat(formatoFecha);
         cn.conectarBD();
        this.jtVenta.setModel(cn.hventa(this.jtVenta));
        this.model = (DefaultTableModel) jtVenta.getModel();
    }

                @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/images/logo-M&M-64x64.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtDetalle = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVenta = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rdbPer = new javax.swing.JRadioButton();
        rdbMensual = new javax.swing.JRadioButton();
        rdbDiario = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fecha1 = new datechooser.beans.DateChooserCombo();
        fecha2 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial de Ventas");
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial de Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jtDetalle.setBackground(new java.awt.Color(51, 51, 51));
        jtDetalle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtDetalle.setForeground(new java.awt.Color(255, 255, 255));
        jtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDetalle.setRowHeight(20);
        jtDetalle.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jtDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jtDetalle);

        jtVenta.setBackground(new java.awt.Color(51, 51, 51));
        jtVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtVenta.setForeground(new java.awt.Color(255, 255, 255));
        jtVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Empleado", "Fecha", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVenta.setRowHeight(20);
        jtVenta.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jtVenta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtVenta.getTableHeader().setResizingAllowed(false);
        jtVenta.getTableHeader().setReorderingAllowed(false);
        jtVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtVenta);
        if (jtVenta.getColumnModel().getColumnCount() > 0) {
            jtVenta.getColumnModel().getColumn(0).setMinWidth(50);
            jtVenta.getColumnModel().getColumn(0).setMaxWidth(50);
            jtVenta.getColumnModel().getColumn(1).setMinWidth(300);
            jtVenta.getColumnModel().getColumn(1).setMaxWidth(300);
            jtVenta.getColumnModel().getColumn(3).setMinWidth(50);
            jtVenta.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/btnRegresar.png"))); // NOI18N
        jButton3.setText("Menú");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        buttonGroup1.add(rdbPer);
        rdbPer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbPer.setText("Personalizada");

        buttonGroup1.add(rdbMensual);
        rdbMensual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbMensual.setText("Mensual");

        buttonGroup1.add(rdbDiario);
        rdbDiario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbDiario.setText("Diaria");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Desde:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hasta:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/btnBuscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fecha1.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        fecha1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        fecha2.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        fecha2.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbPer)
                            .addComponent(jLabel2)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdbMensual)
                                .addGap(43, 43, 43)
                                .addComponent(rdbDiario))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPer)
                    .addComponent(rdbMensual)
                    .addComponent(rdbDiario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.rdbPer.isSelected())
        {
            try {
                cn.conectarBD();
                String query = "SELECT V.idVenta, CONCAT(E.nombre, ' ', E.apellido), V.venta_fecha, V.venta_total FROM venta V "+
                " INNER JOIN empleado E ON E.empleado_code = V.empleado_code "
                + "WHERE venta_fecha >= '"+this.fecha1.getText()+"' AND venta_fecha <= '"+this.fecha2.getText()+"';";
                jtVenta.setModel(cn.buscarCompra(jtVenta, query));
                if (this.jtDetalle.getRowCount() >0)this.modeloDetalle.setRowCount(0);
                cn.conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR: " + ex.toString());
            }
        }
        else
        {
            if(this.rdbDiario.isSelected())
            {
                try {
                    cn.conectarBD();
                    String query = "SELECT V.idVenta, CONCAT(E.nombre, ' ', E.apellido), V.venta_fecha, V.venta_total FROM venta V "+
                    " INNER JOIN empleado E ON E.empleado_code = V.empleado_code "
                    + "WHERE venta_fecha= CURDATE();";
                    jtVenta.setModel(cn.buscarCompra(jtVenta, query));
                    if (this.jtDetalle.getRowCount() >0)this.modeloDetalle.setRowCount(0);
                    cn.conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "ERROR: " + ex.toString());
                }
            }
            else
            {
                try {
                    cn.conectarBD();
                    String query = "SELECT V.idVenta, CONCAT(E.nombre, ' ', E.apellido), V.venta_fecha, V.venta_total FROM venta V "+
                    " INNER JOIN empleado E ON E.empleado_code = V.empleado_code "
                    + "WHERE month(venta_fecha) = MONTh(CURDATE());";
                    jtVenta.setModel(cn.buscarCompra(jtVenta, query));
                    if (this.jtDetalle.getRowCount() >0)this.modeloDetalle.setRowCount(0);
                    cn.conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "ERROR: " + ex.toString());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVentaMouseClicked
        if (this.jtVenta.getSelectedRows().length ==1) {
            try {
                cn.conectarBD();
                String codeCompra =String.valueOf(model.getValueAt(jtVenta.getSelectedRow(),0));
                modeloDetalle = cn.vDetalle(jtDetalle, codeCompra);
                this.jtDetalle.setModel(modeloDetalle);
                cn.conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR: " + ex.toString());
            }

        }
    }//GEN-LAST:event_jtVentaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Hist_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Hist_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Hist_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Hist_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_Hist_Venta().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_Hist_Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    datechooser.beans.DateChooserCombo fecha1;
    datechooser.beans.DateChooserCombo fecha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtDetalle;
    private javax.swing.JTable jtVenta;
    private javax.swing.JRadioButton rdbDiario;
    private javax.swing.JRadioButton rdbMensual;
    private javax.swing.JRadioButton rdbPer;
    // End of variables declaration//GEN-END:variables
}
